name: flutter_native_bridge
description: "Zero-boilerplate bridge between Flutter and native platforms. Call native Kotlin/Swift methods from Dart with minimal setup - just annotate and call!"
version: 1.1.0
homepage: https://github.com/UttamPanchasara/flutter-native-bridge
repository: https://github.com/UttamPanchasara/flutter-native-bridge
issue_tracker: https://github.com/UttamPanchasara/flutter-native-bridge/issues

topics:
  - native
  - bridge
  - android
  - ios
  - platform-channel

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  flutter_native_bridge: generate

flutter:
  plugin:
    platforms:
      android:
        package: io.nativebridge
        pluginClass: FlutterNativeBridgePlugin
      ios:
        pluginClass: FlutterNativeBridgePlugin
